### ISSUE TITLE
seperatıon

### ISSUE THREAD

**Issue by VB10** [MrBuluc/mvrg_app#1]
https://github.com/MrBuluc/mvrg_app/blob/aa2e60a93c64f3861a2e78c7c50c6d66b911af39/lib/viewmodel/user_model.dart#L21

çok fazla iç içe girmiş kodlar parçalanması gerekir businesslerin
immutable kuralına uygun geliştirme yapabilriiz o content değerini set etme kısımları vs için
commentler ile açıklamalar çok eksik try catch kullanımı çok fazla düşürülmeli ve print error loglar bir yerde toplanıp prod mod vs dikkaedilmeli

**Comment by MrBuluc** [comment]
Vakit ayırıp projemi incelediğiniz için teşekkür ederim hocam. Sonraki projelerimde önerilerinizi dikkate alacağım.
