### ISSUE TITLE
class ve dogru yer

### ISSUE THREAD

**Issue by VB10** [MrBuluc/mvrg_app#2]
https://github.com/MrBuluc/mvrg_app/blob/aa2e60a93c64f3861a2e78c7c50c6d66b911af39/lib/ui/const.dart#L5

cok fazla sey bunun ıcınde const olarak soylenmıs ama olmaynalar var sınıf yapılmalı ve bunların ıcınde singleton kuralına uygun veya doğrudan magic number v erilmeli

**Comment by MrBuluc** [comment]
Evet hocam haklısınız. Bu proje eski bir proje o zamanlar acemiliğime gelmiş 😅. Yeni projelerimde daha dikkatli olacağım.
